export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL'

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL'

export const USER_LISTENER_REQUEST = 'USER_LISTENER_REQUEST'
export const USER_LISTENER_SUCCESS_AUTH = 'USER_LISTENER_SUCCESS_AUTH'
export const USER_LISTENER_FAILED_AUTH = 'USER_LISTENER_FAILED_AUTH'
export const USER_LISTENER_FAIL = 'USER_LISTENER_FAIL'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL'

export const UPDATE_USER_DATA_REQUEST = 'UPDATE_USER_DATA_REQUEST'
export const UPDATE_USER_DATA_SUCCESS = 'UPDATE_USER_DATA_SUCCESS'
export const UPDATE_USER_DATA_FAIL = 'UPDATE_USER_DATA_FAIL'

export const SUBSCRIBE_TO_USER = 'SUBSCRIBE_TO_USER'

export const RESET_USER_STORE = 'RESET_USER_STORE'
export const RESET_USER_WITHOUT_CRED = 'RESET_USER_WITHOUT_CRED'